[package]
name = "rust_spider"
version = "0.1.0"
edition = "2021"

[dependencies]
playwright = "0.0.18"
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
thiserror = "2.0.21"
anyhow = "1.0.104"
calamine = "0.36.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
